import Head from 'next/head'
import Header from '../components/Header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google v1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>   

    {/*Header*/  }
    <Header/>
    

    {/*Body*/}

    

    {/*Footer */} 

    </div>
  )
}
